### PR TITLE
connectback-host option

### PR DESCRIPTION
**Pull request by hubert3**
Add a connect back IP module option to be sent to the remote system

This IP can be different to the local IP used for binding

This is necessary for situations where CME is behind NAT and port forwarding has to be used for target systems to connect back to CME.

Successfully tested with the mimikatz module.

### CODE REVIEW

**Comment by byt3bl33d3r** [comment]
Delaying until i can properly test this as I have a feeling this will unexpectedly  break a **LOT** of things.

**Comment by mpgn** [comment]
There is no update on the code, what should I review @hubert3 ?

**Comment by macrl2000** [comment]
this feature is also badly needed for docker install - i tried to follow in code paths but its too complex for me to fix, without breaking other stuff.

for example when you run mimikatz, the powershell module tries to grab payload from the wrong ip.

...
$request = [System.Net.WebRequest]::Create('https://172.17.0.2:443/')
...

**Comment by mpgn** [comment]
no update, closed.

**Pull request closed without merging**
