### PR TITLE
Pwn3d --> Administrator

### PR DESCRIPTION
**Pull request by alexionescu**
Maybe consider this.

### CODE REVIEW

**Comment by byt3bl33d3r** [comment]
but... i really like l33tspeak.

**Comment by aj-cgtech** [comment]
How about a config file parameter ?
I have already implemented it if interested. 

I would submit a pull request, but unsure of the correct procedure, ie: how to modify someones else's pull request :(

**Comment by byt3bl33d3r** [comment]
@aj-cgtech i don't think it merits introducing more complexity for something as silly as this. 
@alexionescu could we compromise with maybe `Adm1n15t4t0r`?

**Comment by aj-cgtech** [comment]
In some cases, when I have copied and pasted, cme output into reports, and then presented the report to the customer, the presence of leetspeak, has caused some issues. Some think it's unprofessional, others just don't know what it means. 
So I think the option to change it easily is good to have imho, I will certainly keep the code in my working branch.

**Comment by CapitanShinChan** [comment]
Well, don't blame the tool for your mistakes.

Presenting a good report is an important part of a security assessment, if you don't dedicate time to "solve" that issues, it's not CME's fault.

**Comment by aj-cgtech** [comment]
I have, solved it, as I said, I've already implemented the fix. It's just not been accepted.

**Comment by byt3bl33d3r** [comment]
As much as I like l33tspeak and would prefer not to take the fun out of everything, I do see @aj-cgtech 's point. If you have the changes in the same branch as the other PR you submitted you can just push the changes there and I'll review it.

**Comment by aj-cgtech** [comment]
Cool, I will merge the changes with one of the other PR's later. 

Thanks for all your efforts btw, it is an awesome tool :)

**Comment by alexionescu** [comment]
My concerns are the same as @aj-cgtech , not trying to take the fun out of this. You guys can close this if it ends up getting added as a config parameter in the other PR.

**Comment by byt3bl33d3r** [comment]
Resolved in https://github.com/byt3bl33d3r/CrackMapExec/commit/f3465ef0080ae56aa64fb2d89aaf7cf7bf253aa0. There's now a new `pwn3d_label` option in the config file (`~/.cme/cme.conf`) that you can use to change the 'Pwn3d!' label to something more boring if you so desire.

Cheers

**Pull request closed without merging**
