### PR TITLE
Added LDAP module to list AD sites and subnets

### PR DESCRIPTION
**Pull request by p0dalirius**
Added LDAP module to list AD sites and subnets

cme_example

## References
 - https://podalirius.net/en/articles/active-directory-sites-and-subnets-enumeration/

### CODE REVIEW

**Review by mpgn — CHANGES_REQUESTED** [review]
Can you delete all the useless files ? (.idea/*)

**Review by p0dalirius — COMMENTED** [review]
It's done, sorry for the mistake

**Comment by mpgn** [comment]
Can you git squash all the commit into one please ? :)

**Review by mpgn — CHANGES_REQUESTED** [review]
Can you git squash all the commit into one please ? :)

**Pull request merged**
