### PR TITLE
[LDAP] Query for user groups or group members

### PR DESCRIPTION
**Pull request by RomanRII**
# Description
* Added ability to query all groups an individual belongs to
* Added ability to query all users belonging to an individual group

# Examples
image

image

# In Reference To
Feature Request: https://github.com/Porchetta-Industries/CrackMapExec/issues/793

### CODE REVIEW

**Comment by RomanRII** [comment]
if this would be better placed in a module, let me know and i can port that over

**Comment by Cyb3rC3lt** [comment]
I think this is catered for in certain modules. Try these:

cme ldap 10.110.228.50 -u test -p 'pass' -d test.info -M groupmembership -o USER=testuser

cme ldap 10.136.81.20 -u testuser -p 'testpass!' -M GROUP-MEM -o GROUP='Domain Admins'

**Comment by RomanRII** [comment]
giphy


Just tried it, yep that's exactly what i was looking for. Thank you!

**Comment by Cyb3rC3lt** [comment]
I realise that's very annoying after your hard work so apologies for being a spoil sport. There are a lot of features not documented unfortunately so it's hard to know what cme does sometimes. I only found the groupmembership module by reading the code. Thanks again for your effort and hopefully you have other ideas.

**Comment by RomanRII** [comment]
Ain't no worries at all. I'm glad I ended up on the same path as someone else who had an idea here. Hopefully the next one is an original :D 

Cheers

**Pull request closed without merging**
