### PR TITLE
Add privilege escalation MSSQL module

### PR DESCRIPTION
**Pull request by sokaRepo**
Hi,

This module performs MSSQL privilege escalation checks:
- dbowner & trustworthy database
- impersonation

The module tries to build an attack path which leads to sysadmin privilege.
Bellow there are two privilege escalation scenarios.

1. impersonation chain + dbowner + trustworthy

| user   |  can impersonate  |  privilege |  sysadmin  |
|---------|------------------------- |-------------|---------------|
|oldbackup|backup|No| No|
|backup|elisee_user|No| No|
|elisee_user|N/A|dbowner| No|

To look for an attack path:
scenar-1-enum

To escalate:
scenar-1-esc

2. impersonation chain + sysadmin impersonation

| user   |  can impersonate  |  privilege |  sysadmin  |
|---------|------------------------- |-------------|---------------|
|oldbackup|backup|No| No|
|backup|elisee_user|No| No|
|elisee_user|N/A|No| Yes|

To look for an attack path:
scenar-2-enum

To escalate:
scenar-2-esc

### CODE REVIEW

**Comment by mpgn** [comment]
Nice, I need to check this !

**Comment by mpgn** [comment]
How hard it will be to put an option to revert back oldbackup to his initial privileges ?

**Comment by sokaRepo** [comment]
Hello @mpgn,

To revert back `oldbackup` privileges, you just need to remove its `sysadmin` role.
It seems that `sp_dropsrvrolemember` is the right way to do that.
I can confirm that in few days when I have time :)

**Comment by mpgn** [comment]
The public version is up to date and we can now merge interesting module like yours. Tell me when it's confirmed and we merge :)

**Comment by sokaRepo** [comment]
Hi,

I updated the module which has now a `rollback` action to remove the `sysadmin` role of the current user. Module also supports `IMPERSONATE ANY` permission.

**Comment by mpgn** [comment]
Let me check this

**Comment by mpgn** [comment]
All good for me

image

**Pull request merged**
