### PR TITLE
Add credential import from Metasploit REST API

### PR DESCRIPTION
**Pull request by mkienow-r7**
This adds the option to import credentials from Metasploit's REST API using `cmedb`. The `import metasploit` command has been enhanced with an additional argument to allow the user to provide the method of import from Metasploit, `import metasploit <rpc|api>`. If the argument is left off `import metasploit`, it defaults to `rpc` to avoid disturbing any existing workflows. However, it would be nice to see this removed eventually. The Metasploit workspace credentials are imported from may be specified using a `workspace` option in the Metasploit section of the config file. If this option is not provided it will default to the current CME workspace name.

## Verification

- [x] Install Metasploit Framework MSF5 (master branch)
    - [ ] See [Setting Up a Metasploit Development Environment](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment) until the MSF5 Nightly Installers are available.
- [ ] Run `msfdb init` to initialize both the database and web service
- [ ] Note the web service API token that is provided when the script completes
- [ ] **Verify** MSF database and web service are running
    - [ ] Execute `msfdb status`, the status should report that both database and web service are running
    - [ ] Execute `curl --insecure -H "Accept: application/json" -H "Authorization: Bearer <token>" https://localhost:8080/api/v1/msf/version | python -m json.tool` and you should see a response that contains the Metasploit version.
- [ ] Start `msfconsole` and create creds (see `creds -h` or run modules that will result in credentials being created)
- [ ] Edit `~/.cme/cme.conf` and configure it appropriately based on how you started the MSF web service earlier using `msfdb`
    ```
    [Metasploit]
    ...
    api_base_url = https://localhost:8080
    api_token = TOKEN
    ```
- [ ] Run `cme` to initialize databases
- [ ] Start `cmedb`
- [ ] Run command `proto smb`
- [ ] Run command `creds` and note that no creds are present if using a fresh database
- [ ] Run command `import metasploit api`
- [ ] Run command `creds`
- [ ] **Verify** NTLM hash and Password credentials from Metasploit are now present in the CME database

### Metasploit
```
msf5 > creds
Credentials
===========

host  origin  service  public                private                                                            realm              private_type
----  ------  -------  ------                -------                                                            -----              ------------
                       admin                 notpassword                                                        workgroup          Password
                       admin-wildcard-realm  notpassword123                                                     dont-know-or-care  Password
                                             password without username                                                             Password
                       other                 d19c32489b870735b5f587d76b934283                                                      Nonreplayable hash
                       guest                 guest password                                                                        Password
                       admin                 e2fc15074bf7751dd408e6b105741864:a1074a69b1bde45403ab680504bbdd1a                     NTLM hash
```

### CrackMapExec
```
cmedb (default) > proto smb
cmedb (default)(smb) > creds

+Credentials--------+----------+--------+----------+----------+
| CredID | Admin On | CredType | Domain | UserName | Password |
+--------+----------+----------+--------+----------+----------+

cmedb (default)(smb) > import metasploit api
[+] Metasploit workspace 'default' exists
[+] Metasploit credential import successful
cmedb (default)(smb) > creds

+Credentials---------+-----------+-----------+----------------------+-------------------------------------------------------------------+
| CredID | Admin On  | CredType  | Domain    | UserName             | Password                                                          |
+--------+-----------+-----------+-----------+----------------------+-------------------------------------------------------------------+
| 1      | 0 Host(s) | plaintext | WORKGROUP | admin                | notpassword                                                       |
| 2      | 0 Host(s) | plaintext |           | guest                | guest password                                                    |
| 3      | 0 Host(s) | plaintext |           |                      | password without username                                         |
| 4      | 0 Host(s) | hash      |           | admin                | e2fc15074bf7751dd408e6b105741864:a1074a69b1bde45403ab680504bbdd1a |
| 5      | 0 Host(s) | plaintext |           | admin-wildcard-realm | notpassword123                                                    |
+--------+-----------+-----------+-----------+----------------------+-------------------------------------------------------------------+
```

### CODE REVIEW

**Comment by byt3bl33d3r** [comment]
@mkienow-r7 holy crap this is amazing ! thanks! will review and merge as soon as i can.

CME's database has been overdue for some major improvements.

Cheers!

**Comment by mkienow-r7** [comment]
@byt3bl33d3r Sounds good to me! I'm happy to see you are excited about these changes. I'm interested in getting other security tool creators familiar with the Metasploit REST API. In fact, the team was even tossing around the idea of swapping out the CME database for the Metasploit database via the REST API. I'd love to hear your thoughts since you say its overdue improvements.

**Comment by mkienow-r7** [comment]
@byt3bl33d3r Is there anything I can do to help you regarding the review?

**Comment by byt3bl33d3r** [comment]
@mkienow-r7 sorry been slammed lately, will review everything after Derbycon.

Thanks

**Comment by byt3bl33d3r** [comment]
Quick update on this, Impacket is almost fully ported to Python 3 at this point. I'm probably going to implement these changes during the rewrite.

Thanks again!

**Pull request closed without merging**
