### PR TITLE
Update smartlogin.py to check for administrator

### PR DESCRIPTION
**Pull request by sho-luv**
Added check for administrator access.

### CODE REVIEW

**Comment by byt3bl33d3r** [comment]
@sho-luv Appreciate the PR! Although I don't really see the point in this since you can check the level of privilege the credentials you have by using the ```--shares``` flag.

Comment below if I'm missing something

**Comment by sho-luv** [comment]
So I spend a lot of time on assessments looking for admin accounts. This was the first part of two updates I wanted to make. The second being able to use the pwdump format in the combo file, which seems to not be working currently. I'm not sure if its just mine or the repos. 

By having it print out Administrator at the end of successful it speeds up my work flow. Similar to that of metasploit's smb_login module. We used to have an option to choose to show admin. However it became apparent why would you not want to know immediately if the account was admin or not? By not knowing it adds one more step to my compromising the environment process.

After the pwdump format is added to the combo supported file format we can just run --sam or whatever other tool people use to get the sam hashes and simple pass them back into crackmapexec with a larger list of IPs and know which accounts have admin writes on the other systems. 

If I have to run --shares I'll have to go back and examine which users had which writes and it will just be more time consuming. However it the successful logins have administrator at the end of them I can simply grep out the successful ones. 

Or at least that is my logic. :)

**Comment by byt3bl33d3r** [comment]
@sho-luv just added pwdump format support! thanks for the awesome suggestion. I changed the smart_login function code again so this PR now has conflicts. I do agree that immediately displaying if the creds have admin privs could be useful, I'll see if I can find a nice way of displaying it when testing creds

**Comment by byt3bl33d3r** [comment]
@sho-luv closing this since it's been implemented on v3.0 which will be pushed to master soon. Thanks again!

**Pull request closed without merging**
